#!/bin/sh

REPO_PATH=$(git rev-parse --show-toplevel)
TF_PATH="$REPO_PATH/infra/terraform"

if [ -d "$TF_PATH" ]; then
  # Run terraform fmt on the staged files and add any changes to the commit
  terraform fmt -check -recursive $TF_PATH
  if [ $? -ne 0 ]; then
    echo "Not all Terraform files are properly formatted. Please run 'terraform fmt -recursive' and commit the changes before pushing."
    exit 1
  fi

  pushd "$TF_PATH" > /dev/null
  
  terraform validate
  if [ $? -ne 0 ]; then
    popd > /dev/null
    exit 1
  fi
  popd > /dev/null
else
  echo "Terraform Directory $TF_PATH not found. Skipping validation for this directory."
fi

exit 0
